name: vfinance
region: fra

# Services
services:
  - name: web
    github:
      repo: vinitorcsaba/vfinance
      branch: master
      deploy_on_push: true

    dockerfile_path: Dockerfile

    # Build-time environment variables
    envs:
      - key: VITE_GOOGLE_CLIENT_ID
        scope: BUILD_TIME
        type: SECRET

    # Runtime environment variables
    envs:
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET

    http_port: 8000

    instance_count: 1
    instance_size_slug: basic-xxs

    routes:
      - path: /

# Migration job (runs before deployment)
jobs:
  - name: migrate
    kind: PRE_DEPLOY
    github:
      repo: vinitorcsaba/vfinance
      branch: master

    dockerfile_path: Dockerfile

    # Override CMD to only run migrations
    run_command: |
      cd /app/backend && python -m alembic upgrade head

    instance_count: 1
    instance_size_slug: basic-xxs
