"""add currency to stock_holdings

Revision ID: 3c1b23dd5ae1
Revises: 58dc801724c6
Create Date: 2026-02-08 09:21:33.782061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1b23dd5ae1'
down_revision: Union[str, Sequence[str], None] = '58dc801724c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_holdings', sa.Column('currency', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_holdings', 'currency')
    # ### end Alembic commands ###
