"""add labels tables

Revision ID: 57b88343d52a
Revises: 3c1b23dd5ae1
Create Date: 2026-02-08 22:13:14.720483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b88343d52a'
down_revision: Union[str, Sequence[str], None] = '3c1b23dd5ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('manual_holding_labels',
    sa.Column('manual_holding_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manual_holding_id'], ['manual_holdings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('manual_holding_id', 'label_id')
    )
    op.create_table('stock_holding_labels',
    sa.Column('stock_holding_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_holding_id'], ['stock_holdings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stock_holding_id', 'label_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_holding_labels')
    op.drop_table('manual_holding_labels')
    op.drop_table('labels')
    # ### end Alembic commands ###
