"""add currency values to transactions

Revision ID: 6ebb0051e754
Revises: ec7b07f140cd
Create Date: 2026-02-23 14:54:44.895446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ebb0051e754'
down_revision: Union[str, Sequence[str], None] = 'ec7b07f140cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('value_ron', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('value_eur', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('value_usd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'value_usd')
    op.drop_column('transactions', 'value_eur')
    op.drop_column('transactions', 'value_ron')
    # ### end Alembic commands ###
